// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAAMxVxdwQCwuB6bNJrRtagTbEH_L_Tjo',
    appId: '1:315697997709:web:649ca764a4655c67eb7fc4',
    messagingSenderId: '315697997709',
    projectId: 'loop-fa8ce',
    authDomain: 'loop-fa8ce.firebaseapp.com',
    storageBucket: 'loop-fa8ce.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0YyapAMrKU35B5wQbdOhLkWHQNaGj1IY',
    appId: '1:315697997709:android:7246eb51350d30e2eb7fc4',
    messagingSenderId: '315697997709',
    projectId: 'loop-fa8ce',
    storageBucket: 'loop-fa8ce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXT3oD_x3MbMrN-a61f0R2CKqCO6ZIVjo',
    appId: '1:315697997709:ios:0713f17f93049d84eb7fc4',
    messagingSenderId: '315697997709',
    projectId: 'loop-fa8ce',
    storageBucket: 'loop-fa8ce.appspot.com',
    iosBundleId: 'com.upcycling.loop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXT3oD_x3MbMrN-a61f0R2CKqCO6ZIVjo',
    appId: '1:315697997709:ios:bbe2d5b227dd572feb7fc4',
    messagingSenderId: '315697997709',
    projectId: 'loop-fa8ce',
    storageBucket: 'loop-fa8ce.appspot.com',
    iosBundleId: 'com.example.loop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAAMxVxdwQCwuB6bNJrRtagTbEH_L_Tjo',
    appId: '1:315697997709:web:055a86705257c677eb7fc4',
    messagingSenderId: '315697997709',
    projectId: 'loop-fa8ce',
    authDomain: 'loop-fa8ce.firebaseapp.com',
    storageBucket: 'loop-fa8ce.appspot.com',
  );
}
